name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        build_type: [Release, Debug]
    steps:
    - uses: actions/checkout@v2
    - name: Configure libmemcpy
      env:
        CC: /usr/bin/${{ matrix.cc }}
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
    - name: Build libmemcpy
      run: |
        cd build
        make -j$(nproc)
    - name: Build examples
      run: |
        cd build
        make -j$(nproc) examples
    - name: Test detect
      run: ./build/examples/detect
    - name: Run benchmark
      run: ./build/examples/bench

  windows-cross:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
    steps:
    - uses: actions/checkout@v2
    - name: Install Windows cross-compile dependencies
      run: |
        sudo apt-get install gcc-mingw-w64-x86-64
    - name: Configure libmemcpy
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=../toolchain-mingw64.cmake \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          ..
    - name: Build libmemcpy
      run: |
        cd build
        make -j$(nproc)
    - name: Build examples
      run: |
        cd build
        make -j$(nproc) examples

  windows-native:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure libmemcpy
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
    - name: Build libmemcpy
      run: |
        cd build
        mingw32-make "-j$([Environment]::ProcessorCount)"
    - name: Build examples
      run: |
        cd build
        mingw32-make "-j$([Environment]::ProcessorCount)" examples
    - name: Test detect
      run: build\examples\detect
    - name: Run benchmark
      run: build\examples\bench
