name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        build_type: [Release, Debug]
    steps:
    - uses: actions/checkout@v2
    - name: Configure libmemcpy
      env:
        CC: /usr/bin/${{ matrix.cc }}
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
    - name: Build libmemcpy
      run: |
        cd build
        make -j$(nproc)
    - name: Build examples
      run: |
        cd build
        make -j$(nproc) examples
    - name: Test detect
      run: ./build/examples/detect

  windows-native:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure libmemcpy
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
    - name: Build libmemcpy
      run: |
        cd build
        mingw32-make "-j$([Environment]::ProcessorCount)"
    - name: Build examples
      run: |
        cd build
        mingw32-make "-j$([Environment]::ProcessorCount)" examples
    - name: Test detect
      run: build\examples\detect
